version: '3.4'

services:
TestAPI:
    image: docker-testAPI
    build:
      context: .
      dockerfile: TestWebApi/Dockerfile
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44301
      - VIRTUAL_HOST=demo.ktevotech.co.th
    ports:
      - "8001:80"
      - "44301:443"
    networks:
      - nginx-proxy
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro